#配置信息
server:
  port: 8888
  Context-path: /music
music:
  kg:
    listUrl: http://mobilecdn.kugou.com/api/v3/search/song?format=jsonp&keyword=%s&page=%s&pagesize=%s&showtype=1
    detailUrl: http://m.kugou.com/app/i/getSongInfo.php?cmd=playInfo
  qmsq:
    listUrl: http://c.y.qq.com/soso/fcgi-bin/search_for_qq_cp?format=json&ie=utf-8&zhidaqu=1&catZhida=1&t=0&flag=1&sem=1&aggr=1&w=%s&perpage=%s&n=%s&p=%s&remoteplace=txt.mqq.all
    detailUrl: http://c.y.qq.com/v8/playsong.html
